services:
  chatbot:
    build:
      context: ./chatbot
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    depends_on:
      - chatbot
    ports:
      - "8501:8501"    